services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 4321
    volumes:
      - app_data:/app/data

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
    depends_on:
      - app

volumes:
  nginx_logs:
  nginx_cache:
  app_data:
